version: '3'

services:
  django-demo:
    build: .
    image: tehcon/django-demo
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8000:8000"
    container_name: django-demo-container